name: REACT deploy                   # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - dev                        
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
      
      - name: Check Node v            # Node v 확인
        run: node -v
      
      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_UMEDI_URL=$REACT_APP_UMEDI_URL" >> .env
          echo "REACT_APP_UMEDI_ACCESS_TOKEN=$REACT_APP_UMEDI_ACCESS_TOKEN" >> .env
          echo "REACT_APP_UMEDI_GOOGLE_MAP_API_TOKEN=$REACT_APP_UMEDI_GOOGLE_MAP_API_TOKEN" >> .env
          echo "CI=false" >> .env
        env:
          REACT_APP_UMEDI_URL: ${{ secrets.REACT_APP_UMEDI_URL }}
          REACT_APP_UMEDI_ACCESS_TOKEN: ${{ secrets.REACT_APP_UMEDI_ACCESS_TOKEN }}
          REACT_APP_UMEDI_GOOGLE_MAP_API_TOKEN: ${{ secrets.REACT_APP_UMEDI_GOOGLE_MAP_API_TOKEN }}

      - name: Install dependencies    # 의존 파일 설치
        run: npm install
      
      - name: Generate build          # React Build
        run: npm run build
        env: 
          CI: ""
      
      - name: Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://umedi-front
